### ISSUE TITLE
Save and load issue

### ISSUE THREAD

**Issue by okvlam** [AI4Finance-LLC/ElegantRL#11]
Thanks so much for the contribution to reinforcement learning.
Might I ask that is there any save and load functions?
Sometimes we might want to stop the training process and continue the training later.

**Comment by Yonv1943** [comment]
Ok, I will add this function in complete version.

I used to add this function but I remove it In order to reduce the amount of code in simple version.

I plan to provide two versions: 
- Simple version. Readable first and high-performence second. (Less code).
- Complete version. High-performence first and readable second. (More code and more functions, including **Save and load**, stop and resume training, multiple processes, distributional computing, etc.
